[package]
name = "stck-interpreter"
version = "0.1.0"
edition = "2024"

[dependencies]
stck = { path = "../lang" }
clap = { version = "4.5.40", features = ["derive"] }
colored = "3.0.0"

[[bin]]
path = "src/main.rs"
name = "stck"
